### ISSUE TITLE
An error occured <class 'FileNotFoundError'>

### ISSUE THREAD

**Issue by Reznovski** [chpoit/utsushis-charm#20]
Followed instructions to the letter, everything is fine until it gets to extracting charms from frames and hit me with the above error. Attached is the app.txt file.
[app.log](https://github.com/chpoit/utsushis-charm/files/6576124/app.log)

**Comment by chpoit** [comment]
I think I know what might have happened, if you go into your AppData/local directory (you can type %LOCALAPPDATA% in the start menu to access it ), is there a folder named "utsushis-charm"? If it's not there please create it manually.

To be certain it should work, I also added the corrections file that should be created manually. Please put that file in the directory if it's not there. 
[corrections.eng.csv](https://github.com/chpoit/utsushis-charm/files/6576579/corrections.eng.csv)

If both the directory and the file are there, please tell me.

If this fixes the issue, I will publish a new release with a fix.

**Comment by Reznovski** [comment]
Alright! Just manually creating the folder fixed the issue and it now works
fine.

**Comment by Reznovski** [comment]
Actually, it seems it hasn't worked properly. The process says it has
completed successfully and has saved the charms to the json and txt files,
but the txt file is empty.

**Comment by chpoit** [comment]
Is there anything in your "frames" directory?

**Comment by Reznovski** [comment]
Yeah, all the different frames are there and sure, i'll attach it here

https://user-images.githubusercontent.com/85170780/120334075-3dcd5480-c2e8-11eb-9b57-b5941f1afeba.mp4

**Comment by chpoit** [comment]
Is it possible that your capture cards records at a resolution under 720p or with a whole lot of blur? The frames and the video are way too blurry.

If you're recording with obs, it's possible that it's upscaling a 480p feed and saving it as a 720p file. It might also directly be your capture card.

**Comment by Reznovski** [comment]
It possibly might be
I'll have a play around with the settings on streamlabs obs, it could also be I accidentally set my capture card to performance over resolution.
I'll give it another go and let you know.

**Comment by Reznovski** [comment]
Turns out it's my capture card or capture program, nothing was working with any of the settings i changed. It worked fine once i got the video straight from the switch however. Might want to point out theres issue with using the Genki Shadowcast for game capture. Apologies for wasting your time.

**Comment by chpoit** [comment]
No worries, your issue did help me find a bug in how I managed the creation of the local directory, I'll add a note regarding the shadowcast resolution.

Here are my Shadowcast settings if you want to try reproducing them. Make sure you set the resolution to 1080p in the dropdown.
![image](https://user-images.githubusercontent.com/17057889/120342744-14033600-c2c6-11eb-9f95-ba2b1bfd009b.png)
