### ISSUE TITLE
An error occured <class 'src.tesseract.TesseractError.TesseractError'>

### ISSUE THREAD

**Issue by septboyboy** [chpoit/utsushis-charm#24]
Input video location:  inputs
Frame location:  frames
Autosaving Charms:  True
Skipping frame extraction:  False
Deleting existing frames:  False
Extracting Frames
Total input files to scan: 1
60 fps video detected, skipping 50% of the frames

Reduced frames from 6298 to 650
Extracting charms from frames
Using bundled tesseract
Language pack was found
An error occured <class 'src.tesseract.TesseractError.TesseractError'>

App.log showed

src.__main__ - ERROR - An error occured <class 'src.tesseract.TesseractError.TesseractError'>, initialization failed (-1), <traceback object at 0x000002228E861C00>
src.__main__ - ERROR - An error occured
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "src\ui\MainWindow.py", line 278, in run
  File "src\ui\MainWindow.py", line 253, in run
  File "src\charm_extraction.py", line 221, in extract_charms
  File "src\tesseract\Tesseract.py", line 86, in __init__
src.tesseract.TesseractError.TesseractError: initialization failed (-1)

**Comment by chpoit** [comment]
Ah sorry, I completely forgot to get back to you on reddit, would you mind uploading the recording you used? It might not be the actual issue, but I'll check it out when I have time.

**Comment by septboyboy** [comment]
https://drive.google.com/file/d/14enDhhLDAwOn0YmifO4FFYWOd6klOR2_/view?usp=sharing

> Ah sorry, I completely forgot to get back to you on reddit, would you mind uploading the recording you used? It might not be the actual source of the issue, but I'll check it out when I have time.

**Comment by septboyboy** [comment]
I actually tried using v131 and it manage to produce charms.encoded.txt

**Comment by chpoit** [comment]
In the meantime, if you could place this file 
https://raw.githubusercontent.com/tesseract-ocr/tessdata/main/eng.traineddata
inside the `utsushis-charm/tessdata` directory. Github changed URLs and it's likely why it's failing.

In windows, the directory will either be in `C:\Users\<USERNAME>\utsushis-charm/tessdata` or `%localappdata%\utsushis-charm/tessdata`

**Comment by septboyboy** [comment]
![Screenshot 2022-02-04 020316](https://user-images.githubusercontent.com/10363457/152402041-e9a98061-7a68-4da3-a641-90957d57b35c.png)
Thanks for the new file, However, now i get this parsing prompt, after keying in the skill it doesnt allow me to enter skill name.

**Comment by chpoit** [comment]
Yeah... for some reason

**Comment by septboyboy** [comment]
Duly noted, Charm extraction complete!
Thank you for your hard work!
