### ISSUE TITLE
utsushis-charm Appdata folder not properly created on initial run

### ISSUE THREAD

**Issue by JoeB98** [chpoit/utsushis-charm#31]
**Device**
- PC
- Game language: English
- App version: 1.6.1

Note: app.log didn't properly fill, but unhandled exception error threw this:
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "src\__main__.py", line 103, in main
  File "src\resources.py", line 193, in get_app_language
  File "src\resources.py", line 181, in _load_config
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Joe\\AppData\\Local\\utsushis-charm\\config.json'
```

This happens on initial run of the program(with clip properly in inputs folder), failing to generate the AppData folder and items within it. Downloading 1.6.0 release and running it properly created AppData folder and generated folder/files, which then allowed 1.6.1 to run properly on the clip.

As the clip itself worked properly after the workaround, I don't believe it was the particular issue, but I could be wrong.

**Comment by chpoit** [comment]
Quite the frustrating issue, I'm building a new version now and it should be uploaded in a few minutes
