### ISSUE TITLE
Tesseract initialization issues

### ISSUE THREAD

**Issue by chpoit** [chpoit/utsushis-charm#32]
I went ahead and tried the new version, and I am getting a new error now. I am also able to see the app.log file now after using this new version.  1st is error in the program, 2nd is error in the app.log .

```
Input video location:  inputs
Frame location:  frames
Autosaving Charms:  True
Skipping frame extraction:  True
Deleting existing frames:  False
Extracting charms from frames
Checking for bundled tesseract
Tesseract: C:\Users\PWRWa\AppData\Local\Temp\_MEI68002\libtesseract-5.dll
Language pack was found
An error occured <class 'src.tesseract.TesseractError.TesseractError'> <traceback object at 0x00000211F8D88D80>
```

```
src.__main__ - ERROR - An error occured <class 'src.tesseract.TesseractError.TesseractError'>, initialization failed (-1), <traceback object at 0x00000211F8D88D80>
src.__main__ - ERROR - An error occured
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "src\ui\MainWindow.py", line 345, in run
  File "src\ui\MainWindow.py", line 322, in run
  File "src\charm_extraction.py", line 221, in extract_charms
  File "src\tesseract\Tesseract.py", line 86, in __init__
src.tesseract.TesseractError.TesseractError: initialization failed (-1)
```

_Originally posted by @Capsdual in https://github.com/chpoit/utsushis-charm/issues/29#issuecomment-1175512232_

taken from #29

**Comment by chpoit** [comment]
Hey @Capsdual you might think i'm crazy, but try installing windows updates, I just created a new virtual machine with nothing installed and I was able to run your clips. 

If that doesn't do it, I don't think I can actually fix this, I tried on two W11 "Computers", I even packaged the app on W11, and it works everywhere for me.

I genuinely hope this isn't a "this works on my computer" thing, but it might be.

**Comment by Sundava** [comment]
Hi, just chiming in to say I have the same issue, but with the bundled version of tesseract on Windows 10
I also tried manually installing and using the JSON you provided  
(With double `\\` instead of `\`, it fails because of invalid JSON otherwise)

**Comment by Capsdual** [comment]
Still no dice unfortunately, tried updating and changing between Tesseract-OCR and Tesseract-OCR/libtesseract-5.dll along with deleting the AppData folder for the program and deleting Tesseract and moving it to another drive. 

```
 Input video location:  inputs
Frame location:  frames
Autosaving Charms:  True
Skipping frame extraction:  True
Deleting existing frames:  False
Extracting charms from frames
Checking for bundled tesseract
Tesseract: C:\Program Files\Tesseract-OCR\libtesseract-5.dll
Language pack was found
An error occured <class 'src.tesseract.TesseractError.TesseractError'> <traceback object at 0x0000029B3D4115C0>
```

**Comment by chpoit** [comment]
> Hi, just chiming in to say I have the same issue, but with the bundled version of tesseract on Windows 10 (Up to date, too) I also tried manually installing and using the JSON you provided , to no avail (With double `\\` instead of `\`, it fails because of invalid JSON otherwise)

Good catch thanks



Could you guys having tesseract issues give me some info about your computer such as
- CPU type
- GPU type
- how much ram
- ssd vs hdd
- full windows version (like 1206.something,or whatever it's at) 
- do you have python installed from the windows store, regular download, or not installed
- anything else you think might be pertinent
-
I hate to say it, but there is a good chance I can't fix this

**Comment by Sundava** [comment]
Hi, seems like uninstalling and reinstalling the folder in AppData fixed it for me.
In case it helps: It tried to parse the frame the first time, and managed to process about 70% of the input clip, but then became unresponsive and had to be killed.

The subsequent tries failed with the traceback mentioned at the beginning of the ticket, even without anything in the `frames` or `inputs` folders.

**Comment by Sundava** [comment]
It was something really small, like 8.6 MB. I seem to be able to reproduce it consistently when using the old folder from `AppData`, so maybe with this you'll be able to investigate further:

[utsushis-charm.zip](https://github.com/chpoit/utsushis-charm/files/9054817/utsushis-charm.zip)

I built the repo from source too, but I can't reproduce the bug this way, only from the executable.

**Comment by chpoit** [comment]
@Capsdual could you try using the "latest" version of tesseract that is [available here](https://digi.bib.uni-mannheim.de/tesseract/) 
right now it should be the 5.1.0 release (the windows version ships with 5.0.1). Make sure you pick the "w64" version, it should be the last one.

Google released ~40 minutes ago (as of writing this) a new 5.2.0 release. It took ub manheim ~2 months to release 5.1 last time, so it might take a while for it to be easily available for windows, but I'll try to check from time to time.

**Comment by Capsdual** [comment]
> @Capsdual could you try using the "latest" version of tesseract that is [available here](https://digi.bib.uni-mannheim.de/tesseract/) right now it should be the 5.1.0 release (the windows version ships with 5.0.1). Make sure you pick the "w64" version, it should be the last one.
> 
> Google released ~40 minutes ago (as of writing this) a new 5.2.0 release. It took ub manheim ~2 months to release 5.1 last time, so it might take a while for it to be easily available for windows, but I'll try to check from time to time.

Unfortunately that didn't work either. I also checked to see if it was a permissions issue and ran into the same result. Weirdly enough, I also tried a VM of Windows 10 and Windows 11 before I went to sleep yesterday and I ran into the same issue both times. I would attempt with linux or some other way, but I am really not versed with those.

**Comment by Sundava** [comment]
> Now that is odd, I just checked the md5 sum off your eng.traineddata and it's different from mine, and it's also smaller.
> 
> * My md5sum: 57e0df3d84fed9fbf8c7a8e589f8f012 (22.4mib)
> * Your md5sum: 89780d2ebcd30ca800d4b17b80016626 (21.6mib)
> 
> Could you drag and drop your "new one" (it should be in the tessdata folder) on [this online checker](https://emn178.github.io/online-tools/md5_checksum.html) and tell me the result? It might just be due to a partially failed download, or a "corrupted version", but the former is unlikely given that the [last time the eng file was changed was 4 years ago](https://github.com/tesseract-ocr/tessdata)

The checksum of the new, working `eng.traineddata` is indeed the same as yours `57e0df3d84fed9fbf8c7a8e589f8f012`, so I assume it was a matter of corrupted file  
(I reinstalled it on a new computer with a bad connection, so I guess the initial download failed midway)

Looks like my issue was unrelated and not a bug after all, sorry for the confusion

**Comment by chpoit** [comment]
> Unfortunately that didn't work either. I also checked to see if it was a permissions issue and ran into the same result after modifying them. Weirdly enough, I also tried a VM of Windows 10 and Windows 11 before I went to sleep yesterday and I ran into the same issue both times and could not get it to work in those either. I would attempt with linux or some other way, but I am really not versed with those methods.
> 
> As for my hardware in the previous post - 5800X / 3080 / 32 GB Ram / SSD / 22000.778 (windows 11) / I tried with python not installed and regular download / English

That is very odd, can you tell me if there is anything in the `AppData/Local/utsushis-charm/tessdata` directory, and if there is could you check the size of the eng.traineddata to make sure it's around 22.4mb? Even if it is could you try [manually downloading it](https://github.com/tesseract-ocr/tessdata/blob/4.1.0/eng.traineddata) just in case you happen to have some weird corrupted download cached somewhere in your network/computer. [Here is a link a copy of "mine"](https://drive.google.com/file/d/1ToMyqfcSCM9iFsE3YJjpAIKbWpT3WyeP/view?usp=sharing) in case the github one still breaks.

- [You could also try the "best" version](https://github.com/tesseract-ocr/tessdata_best/blob/main/eng.traineddata)
- [Or maybe try the "fast" version](https://github.com/tesseract-ocr/tessdata_fast/blob/main/eng.traineddata)

**Comment by chpoit** [comment]
> > Now that is odd, I just checked the md5 sum off your eng.traineddata and it's different from mine, and it's also smaller.
> > 
> > * My md5sum: 57e0df3d84fed9fbf8c7a8e589f8f012 (22.4mib)
> > * Your md5sum: 89780d2ebcd30ca800d4b17b80016626 (21.6mib)
> > 
> > Could you drag and drop your "new one" (it should be in the tessdata folder) on [this online checker](https://emn178.github.io/online-tools/md5_checksum.html) and tell me the result? It might just be due to a partially failed download, or a "corrupted version", but the former is unlikely given that the [last time the eng file was changed was 4 years ago](https://github.com/tesseract-ocr/tessdata)
> 
> The checksum of the new, working `eng.traineddata` is indeed the same as yours `57e0df3d84fed9fbf8c7a8e589f8f012`, so I assume it was a matter of corrupted file (I reinstalled it on a new computer with a bad connection, so I guess the initial download failed midway)
> 
> Looks like my issue was unrelated and not a bug after all, sorry for the confusion

Eh, it helped me figure out that OP's issue might be download/cache based more than anything, you two are the only ones reporting this issue so github's CDNs might have both given you a bad file, and OP is still getting issues due to how his network is configured (I really hope that's it)

In any case, thanks for telling me that the md5 now matches.

**Comment by Capsdual** [comment]
That actually completely fixed the issue for me. Downloading the eng.traineddata from the 1st link you posted and replacing it worked and I was able to extract the charms without any errors.  Old was 17.2 MB / New was 22.3 MB. Not sure where the issues are coming in from with me downloading it and it not being the correct size though.

**Comment by chpoit** [comment]
That's really great to hear, it might be a weird python issue that only happens on specific hardware under specific circumstances, my CPU is a ryzen 9 3950x and I never had that issue, might be a weird ryzen 5000 thing if Sundava is on that too. 

In any case I'm glad this is resolved and let us hope you don't just magically attract cosmic rays that flip bits in a way that your downloads sometimes fail, but not really.

I will be closing this issue now
