### ISSUE TITLE
ERROR - An error occured <class 'KeyError'>

### ISSUE THREAD

**Issue by lbbboy** [chpoit/utsushis-charm#34]
**Device**
- Switch or PC (Where do you play)
  - For PC, what is your screen resolution: 1080P
  - For PC, what is your OS: Microsoft Windows 11 Build 22000
 - Game language: Simplified Chinese
 - App version: v1.6.2

** Problem(s) **
Please describe the issue in as much detail.

```
src.__main__ - ERROR - An error occured <class 'KeyError'>, 'Simplified Chinese', <traceback object at 0x00000231B2FBF7C0>
src.__main__ - ERROR - An error occured
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "src\ui\MainWindow.py", line 345, in run
  File "src\ui\MainWindow.py", line 321, in run
  File "src\resources.py", line 245, in untranslate_lang
KeyError: 'Simplified Chinese'
```
![frame27](https://user-images.githubusercontent.com/7271994/177596518-2e951809-3cb6-4a0e-8cc2-4ff7585f01ec.png)

**Comment by chpoit** [comment]
Thanks for creating the issue, I'll try to figure out why it crashes.

BTW, you need to unequip all jewels. It is nigh impossible to figure out what a specific jewel does.
