### ISSUE TITLE
Level 4 slots identified as level 3 slots

### ISSUE THREAD

**Issue by onionpowder2** [chpoit/utsushis-charm#35]
**Device**
- Switch
  - For PC, what is your screen resolution: N/A
  - For PC, what is your OS: N/A
  - For switch, is your recording at least 720p (ignore if you are using the switch recording feature): Switch recording
- Game language: English
- App version: 1.6.2

** Problem(s) **
The program did not appear to correctly identify level 4 slots as level 4 slots - it simply identified them as level 3 slots instead. There really isn't much more to it than that. This is my first time submitting an issue on GitHub as a whole, so I'm not entirely sure if you need much else to go off of. I'll attach frames of a couple such charms though. Let me know if you need more info.
![frame0](https://user-images.githubusercontent.com/108959396/178078084-09428971-2344-4765-9dfb-6a84f0315f62.png)
![frame448](https://user-images.githubusercontent.com/108959396/178078090-b9f5b68e-0b14-4d92-8e5a-f9dfa776edf0.png)

**Comment by chpoit** [comment]
I'm working on it, should be out this weekend.

**Comment by chpoit** [comment]
Added in #36
