### ISSUE TITLE
MacOS - Tesseract library was not found on your system. Please install it

### ISSUE THREAD

**Issue by druchoo** [chpoit/utsushis-charm#46]
**Device**
- Switch
- Game language: English
- OS: macOS Monterey (12.5.1) - M1
- App version: master (https://github.com/chpoit/utsushis-charm/commit/13b8eaab2cbad1009f4d1d3b9fb07e5d2cd74596)

**app.log contents**
What is in the app.log? It should be located besides the executable.

> src.tesseract.tesseract_utils - ERROR - Tesseract library was not found on your system. Please install it

**Additional context**
Tesseract was installed with Homebrew and app built from source. Issue is the extension of the library is `dylib`. For Monterey (sorry don't have other macOS versions) this applies to both ARM and Intel. Unfortunately, it is not accounted for in the logic for non Windows OSes.

```
❯ ls -go /opt/homebrew/Cellar/tesseract/5.2.0/lib/libtesseract.*
-r--r--r-- 1 2.6M Jul  8 17:54 /opt/homebrew/Cellar/tesseract/5.2.0/lib/libtesseract.5.dylib
-r--r--r-- 1 4.7M Jul  6 16:15 /opt/homebrew/Cellar/tesseract/5.2.0/lib/libtesseract.a
lrwxr-xr-x 1   20 Jul  6 16:15 /opt/homebrew/Cellar/tesseract/5.2.0/lib/libtesseract.dylib -> libtesseract.5.dylib
```

**_Note_**: macOS ARM Homebrew prefix is `/opt/homebrew` vs `/usr/local` for macOS Intel. 

Both of these methods work (for me at least). Didn't need to add the extension to `_get_pyinstaller_tesseract_path` to build from source but maybe it's needed for something else? (I haven't fully reviewed all the code).

1. Create a symlink for `/opt/homebrew/Cellar/tesseract/5.2.0/lib/libtesseract.so.5 -> libtesseract.5.dylib`
2. Update code
```python
def _get_config_tesseract_path():
  ...

        else:
            locations += [
                os.path.join(configLocation, "libtesseract.so.5"),
                os.path.join(configLocation, "libtesseract.so.4"),
                os.path.join(configLocation, "libtesseract.dylib"),  # <-- add this
            ]
    return locations
```

If `2.` sounds like a good enough fix, I can PR that if needed.

**Comment by chpoit** [comment]
Option 2 sounds good, feel free to add the macOS paths via a PR.

I don't own a mac so most of the support for it is "oh look it also works here", thanks in advance for this fix.

**Comment by druchoo** [comment]
@chpoit, The symlink (`libtesseract.dylib`) has no version number but the target (`libtesseract.5.dylib`) does.

https://github.com/chpoit/utsushis-charm/pull/47 to add `libtesseract.dylib`.

And thank you for this app!
