### ISSUE TITLE
Skill name reading issue: Chain Crit -> Burst

### ISSUE THREAD

**Issue by JustAnotherRandomLad** [chpoit/utsushis-charm#50]
**Device**
- PC
  - For PC, what is your screen resolution: 1920x1080
  - For PC, what is your OS: Windows 11
- Game language: English
- App version: 1.8

**Problem(s)**
The Chain Crit skill has been renamed to Burst, which Utsushi's Charm does not recognize as a valid skill name. (I'm unsure whether this skill's name has also been changed in other languages.)

The app also has a tendency to read Horn Maestro and Hellfire Cloak as "Hom Maestro" and "Heillfire Cloak", respectively. You may wish to account for these as with other common misreads.

**Comment by chpoit** [comment]
The latest commit now contains TU2 skills and the chain crit rename

I also added your two proposed corrections to "corrections.eng.csv" where everyone is free to submit new automatic corrections. Next time you start the app it should ask you if you want to download the new skills and corrections.

**Comment by JustAnotherRandomLad** [comment]
Ah, I thought I saw something like that corrections link in the past, but couldn't remember where it was. Thank you!

**Comment by chpoit** [comment]
No worries, I have a lot of them, just not all of them, I never had "Hom" but I had 8 variations of hellfire
