### ISSUE TITLE
new talismens, new skill limitations, old expectations 

### ISSUE THREAD

**Issue by facade11663** [chpoit/utsushis-charm#53]
**Device**
- Switch
  - For switch, is your recording at least 720p: OBS 1080p 
- Game language: English
- App version: 1_8

** Problem(s) **
skills with level 4+ are being omitted. a charm of Earplugs,4,Handicraft,1,2,1,0 is being reported as Handicraft,1,,0,2,1,0
![frame4153](https://user-images.githubusercontent.com/68785992/234149781-68ce552d-7c03-49f5-af99-56b266b1b552.png)

as a side Horn Maestro is being picked up as Hom or Horm

**Comment by chpoit** [comment]
I'll try and take some time over the week to add the new skills/skill levels, Hom/horm/horr \*should\* be in the automatic corrections so it's odd it doesn't get auto-corrected

thanks for the screenshot, it'll save time to add lvl4 skills, do you know if they added lvl5s too, or is 4 the current max

**Comment by facade11663** [comment]
Most skills don't seem to make it past 5 acording to
https://docs.google.com/spreadsheets/d/1iBgTZttW-ECbRUy_9zm_FFuiQbi9LT93KuY-2iK5t_g/edit?usp=drivesdk

defence boost can go all the way to level 7 as a primary skill
