### ISSUE TITLE
Dragon Conversion, Frostcraft not supported. Lvl 5 skills not supported

### ISSUE THREAD

**Issue by Deriboy** [chpoit/utsushis-charm#55]
**Device**
- Switch
- Game language: English 
- OS: Windows 10
- App version: 1.9

**Issue**
- Lvl 5 skills on talismans from new melding don't seem to be supported
- Dragon Conversion and Frostcraft skills aren't supported. The app parses them correctly but asks me to confirm them as it believes they are parse errors.

**Comment by chpoit** [comment]
I added the two skills, do you happen to have a frame with a lvl5 skill, and could you upload the screenshot? I haven't had time to play and I need an image of the "5" for it to detect it. Just parsing the number gave poor results back then.

**Comment by Deriboy** [comment]
Here's a reference image in case you still need it. 

![frame135](https://user-images.githubusercontent.com/3218615/234444689-ce7d469f-e480-4b55-81c7-95836c0fa915.png)

**Comment by Deriboy** [comment]
Awesome, thank you for your work on this project!
